channels:
- conda-forge
- nodefaults
dependencies:
- make
- mypy
- myst-parser
- pre-commit
- sphinx-rtd-theme
- pytest
- pytest-cov
- sphinx
- sphinx-autoapi
- nbsphinx
- array-api-compat
- numpy
- xarray
- geopandas
- earthkit-data[all]
- earthkit-utils
