channels:
- conda-forge
- nodefaults
dependencies:
- earthkit-data
- geopandas
- make
- mypy
- myst-parser
- nbsphinx
- numpy
- pandas-stubs
- pip
- pre-commit
- pydata-sphinx-theme
- pytest
- pytest-cov
- rasterio
- sphinx
- sphinx-autoapi
- sphinx-rtd-theme
- xarray
- pip:
  - git+https://github.com/ecmwf/multiurl
