# environment-ci.yml: Additional dependencies to install in the CI environment.
channels:
- conda-forge
- nodefaults
dependencies:
- make
- mypy
- myst-parser
- pre-commit
- sphinx-rtd-theme
- pytest
- pytest-cov
- sphinx
- sphinx-autoapi
- nbsphinx
- pandas-stubs
- ipykernel
# Deps required for geometry operations in tests and examples
- rasterio
# Both of these are required for earthkit-data when installing from conda-forge:
- array-api-compat
- multiurl
# Required for notebook example
- statsmodels
