name: downstream-ci

on:
  # Trigger the workflow on push to main, excluding tags
  # push:
  #   branches:
  #   - 'main'
  #   tags-ignore:
  #   - '**'
  #   paths-ignore:
  #   - "docs/**"
  #   - "README.md"
  #   - "LICENCE"
  #   - ".gitignore"
  #   - ".readthedocs.yaml"

  # Trigger the workflow manually
  workflow_dispatch:
    inputs:
      branch:
        description: "Branch to deploy from"
        required: true
        default: "main"

# Triggered by other workflows
  workflow_call:


jobs:
  # Run CI including downstream packages on self-hosted runners
  downstream-ci:
    name: downstream-ci
    if: ${{ !github.event.pull_request.head.repo.fork && github.event.action != 'labeled' || github.event.label.name == 'approved-for-ci' }}
    uses: ecmwf/downstream-ci/.github/workflows/downstream-ci.yml@main
    with:
      earthkit-transforms: ecmwf/earthkit-transforms@${{ github.event.pull_request.head.sha || github.sha }}
      codecov_upload: true
      python_qa: false
    secrets: inherit

  # Build downstream packages on HPC
  downstream-ci-hpc:
    name: downstream-ci-hpc
    if: ${{ !github.event.pull_request.head.repo.fork && github.event.action != 'labeled' || github.event.label.name == 'approved-for-ci' }}
    uses: ecmwf/downstream-ci/.github/workflows/downstream-ci-hpc.yml@main
    with:
      earthkit-transforms: ecmwf/earthkit-transforms@${{ github.event.pull_request.head.sha || github.sha }}
    secrets: inherit
